language: python
python:
- '3.7'
sudo: required
install:
- pip install flask
script:
- python test.py
deploy:
  provider: heroku
  app: devopsfbc
  api_key:
    secure: j4bzJmHXXXrTH96PkY4eq3Jp00d3wrmjoX2aCAt7rCHMbQOKX3crXbettOiyVNjVifNHjx4QDQS/ni7Bn8YQ4OmKkegmyMPS/PbJnlhcYwCDdEHL+4VX+vy8g+gGmITR6xfxhi09DcBp1U8sP+TvmEWoLJqXEj+xE5T6OegZvSEdIZOdbXLdW0JxxJgXBDUmj3lyfkEgeWoDI9COkRUqMwMap4XrfW1CKdIaSJnemRKbTjd48PB9KoPOkp+nzxhB/b6MvA6qedeu51GRMlWgWlrZTzP6aa1hzySnnQ22bpCPjFm4TXfBw8UxGEPszzG31BNQXBByylrrh9fgIwWVz32a+Xl0Ypb5jBy57HNocPU063v1570xETN3+pIL60Tqt4ByswzIDPzyNKbPw3SPt4JFlQs4APCXwOetcrl6xzVPE1xrmJ4JtIdFUeFILdhL+WFdIvgf3XbW7bAACI+8DowJ5TCWIr2n7SsXns5+Njet4/njhercKw6q1+iES9bRgzx+b1eSkXKNkcDUZiSaI4oPVZbQBteIAlC2iMo2+zvzrkxRrCYm3LCjkqXTW492Uo0YBkJUH+UtPmwH0avjM+oojkX1LjsWBHSdY8xEmCfUVV5mUjFSZDq9qFX1gxgu8h4kLztED3dzH1Xlw+bMVsvl9pgsL1+TrZkvNqzWmCY=
